# Generated by Django 5.1.4 on 2025-01-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
